from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QValidator, QIntValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 360, 431, 261))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 391, 211))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(11, 51, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBoxSigType = QtWidgets.QComboBox(self.widget_2)
        self.comboBoxSigType.setGeometry(QtCore.QRect(160, 51, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxSigType.setFont(font)
        self.comboBoxSigType.setObjectName("comboBoxSigType")
        self.comboBoxSigType.addItem("")
        self.comboBoxSigType.addItem("")
        self.comboBoxSigType.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        # validator for offset line editor
        validator_off = QIntValidator (-15, 15)
        validator_ampl = QIntValidator (0, 100)
        validator_freq = QIntValidator (0, 10000000)
        #
        ##
        self.lineEditFreq = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditFreq.setGeometry(QtCore.QRect(160, 80, 141, 22))
        self.lineEditFreq.setObjectName("lineEditFreq")
        self.lineEditFreq.setValidator(validator_freq)
        self.lineEditAmplt = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditAmplt.setGeometry(QtCore.QRect(160, 110, 141, 22))
        self.lineEditAmplt.setObjectName("lineEditAmplt")
        self.lineEditAmplt.setValidator(validator_ampl)
        self.lineEditOff = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditOff.setGeometry(QtCore.QRect(160, 140, 141, 22))
        self.lineEditOff.setObjectName("lineEditOff")
        self.lineEditOff.setValidator(validator_off)
        ##
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 551, 211))
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(11, 51, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBoxBitNo = QtWidgets.QComboBox(self.widget_3)
        self.comboBoxBitNo.setGeometry(QtCore.QRect(180, 50, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxBitNo.setFont(font)
        self.comboBoxBitNo.setObjectName("comboBoxBitNo")
        self.comboBoxBitNo.addItem("")
        self.comboBoxBitNo.addItem("")
        self.comboBoxBitNo.addItem("")
        self.comboBoxBitNo.addItem("")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(130, 10, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdiRech = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdiRech.setGeometry(QtCore.QRect(180, 110, 113, 22))
        self.lineEdiRech.setObjectName("lineEdiRech")
        self.lineEditVref = QtWidgets.QLineEdit(self.widget_3)
        self.lineEditVref.setGeometry(QtCore.QRect(180, 140, 113, 22))
        self.lineEditVref.setObjectName("lineEditVref")
        self.lineEditRespTime = QtWidgets.QLineEdit(self.widget_3)
        self.lineEditRespTime.setGeometry(QtCore.QRect(180, 80, 113, 22))
        self.lineEditRespTime.setObjectName("lineEditRespTime")
        self.lineEditVrefLim = QtWidgets.QLineEdit(self.widget_3)
        self.lineEditVrefLim.setGeometry(QtCore.QRect(180, 170, 113, 22))
        self.lineEditVrefLim.setObjectName("lineEditVrefLim")
        self.tabWidget.addTab(self.tab_2, "")
        self.TabCircuit = QtWidgets.QWidget()
        self.TabCircuit.setObjectName("TabCircuit")
        self.widget_6 = QtWidgets.QWidget(self.TabCircuit)
        self.widget_6.setGeometry(QtCore.QRect(10, 10, 541, 211))
        self.widget_6.setObjectName("widget_6")
        self.label_23 = QtWidgets.QLabel(self.widget_6)
        self.label_23.setGeometry(QtCore.QRect(11, 51, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_6)
        self.label_24.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_6)
        self.label_25.setGeometry(QtCore.QRect(10, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.widget_6)
        self.label_27.setGeometry(QtCore.QRect(130, 10, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEditRout = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditRout.setGeometry(QtCore.QRect(220, 50, 113, 22))
        self.lineEditRout.setObjectName("lineEditRout")
        self.lineEditSRAO = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditSRAO.setGeometry(QtCore.QRect(220, 80, 113, 22))
        self.lineEditSRAO.setObjectName("lineEditSRAO")
        self.lineEditValim = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditValim.setGeometry(QtCore.QRect(220, 110, 113, 22))
        self.lineEditValim.setObjectName("lineEditValim")
        self.label_26 = QtWidgets.QLabel(self.widget_6)
        self.label_26.setGeometry(QtCore.QRect(10, 140, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEditValim_2 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditValim_2.setGeometry(QtCore.QRect(220, 140, 113, 22))
        self.lineEditValim_2.setObjectName("lineEditValim_2")
        self.label_28 = QtWidgets.QLabel(self.widget_6)
        self.label_28.setGeometry(QtCore.QRect(10, 170, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.comboBoxEvoSigType = QtWidgets.QComboBox(self.widget_6)
        self.comboBoxEvoSigType.setGeometry(QtCore.QRect(220, 170, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxEvoSigType.setFont(font)
        self.comboBoxEvoSigType.setObjectName("comboBoxEvoSigType")
        self.comboBoxEvoSigType.addItem("")
        self.comboBoxEvoSigType.addItem("")
        self.tabWidget.addTab(self.TabCircuit, "")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(450, 380, 671, 241))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("CMOS_SS.png"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")
        self.comboBoxSchemeType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSchemeType.setGeometry(QtCore.QRect(770, 640, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxSchemeType.setFont(font)
        self.comboBoxSchemeType.setObjectName("comboBoxSchemeType")
        self.comboBoxSchemeType.addItem("")
        self.comboBoxSchemeType.addItem("")
        self.comboBoxSchemeType.addItem("")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(620, 640, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1111, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.PlotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.PlotLayout.setContentsMargins(0, 0, 0, 0)
        self.PlotLayout.setObjectName("PlotLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 620, 431, 80))
        self.widget.setObjectName("widget")
        self.UnitTypeComboBox = QtWidgets.QComboBox(self.widget)
        self.UnitTypeComboBox.setGeometry(QtCore.QRect(200, 10, 51, 21))
        self.UnitTypeComboBox.setObjectName("UnitTypeComboBox")
        self.UnitTypeComboBox.addItem("")
        self.UnitTypeComboBox.addItem("")
        self.UnitTypeComboBox.addItem("")
        self.UnitTypeComboBox.addItem("")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_12.setObjectName("label_12")
        self.DivNoSpinBox = QtWidgets.QSpinBox(self.widget)
        self.DivNoSpinBox.setGeometry(QtCore.QRect(120, 10, 71, 22))
        self.DivNoSpinBox.setMinimum(1)
        self.DivNoSpinBox.setMaximum(10)
        self.DivNoSpinBox.setObjectName("DivNoSpinBox")
        self.InfoPushButton = QtWidgets.QPushButton(self.widget)
        self.InfoPushButton.setGeometry(QtCore.QRect(10, 40, 251, 28))
        self.InfoPushButton.setObjectName("InfoPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        self.menuDocumenta_ie = QtWidgets.QMenu(self.menubar)
        self.menuDocumenta_ie.setObjectName("menuDocumenta_ie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_ndrum_tor_laborator_EA = QtWidgets.QAction(MainWindow)
        self.action_ndrum_tor_laborator_EA.setObjectName("action_ndrum_tor_laborator_EA")
        self.actionPrezentare = QtWidgets.QAction(MainWindow)
        self.actionPrezentare.setObjectName("actionPrezentare")
        self.menuDocumenta_ie.addAction(self.action_ndrum_tor_laborator_EA)
        self.menuDocumenta_ie.addSeparator()
        self.menuDocumenta_ie.addAction(self.actionPrezentare)
        self.menubar.addAction(self.menuDocumenta_ie.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tipul semnalului:"))
        self.label_2.setText(_translate("MainWindow", "Frecvența:"))
        self.label_3.setText(_translate("MainWindow", "Amplitudine:"))
        self.label_4.setText(_translate("MainWindow", "Offset:"))
        self.comboBoxSigType.setItemText(0, _translate("MainWindow", "Dreptunghiular"))
        self.comboBoxSigType.setItemText(1, _translate("MainWindow", "Sinusoidal"))
        self.comboBoxSigType.setItemText(2, _translate("MainWindow", "Triunghiular"))
        self.label_5.setText(_translate("MainWindow", "Parametrii semnal de intrare"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Semnal de intrare"))
        self.label_6.setText(_translate("MainWindow", "Număr biți:"))
        self.label_7.setText(_translate("MainWindow", "Timp de răspuns:"))
        self.label_8.setText(_translate("MainWindow", "R Echivalent:"))
        self.label_9.setText(_translate("MainWindow", "Intrarea de referință:"))
        self.comboBoxBitNo.setItemText(0, _translate("MainWindow", "6"))
        self.comboBoxBitNo.setItemText(1, _translate("MainWindow", "7"))
        self.comboBoxBitNo.setItemText(2, _translate("MainWindow", "8"))
        self.comboBoxBitNo.setItemText(3, _translate("MainWindow", "9"))
        self.label_10.setText(_translate("MainWindow", "Specificatii convertor analogic"))
        self.label_11.setText(_translate("MainWindow", "Limitare referință"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Convertor Analogic"))
        self.label_23.setText(_translate("MainWindow", "Rezistența de ieșire:"))
        self.label_24.setText(_translate("MainWindow", "Slew rate AO:"))
        self.label_25.setText(_translate("MainWindow", "Tensiunea de alimentare:"))
        self.label_27.setText(_translate("MainWindow", "Specificații montaj"))
        self.label_26.setText(_translate("MainWindow", "Durata tactului: "))
        self.label_28.setText(_translate("MainWindow", "Tipul de evoluție: "))
        self.comboBoxEvoSigType.setItemText(0, _translate("MainWindow", "Numărător"))
        self.comboBoxEvoSigType.setItemText(1, _translate("MainWindow", "Astabil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabCircuit), _translate("MainWindow", "Montaj"))
        self.comboBoxSchemeType.setItemText(0, _translate("MainWindow", "D/A Bipolar Ieșire în curent"))
        self.comboBoxSchemeType.setItemText(1, _translate("MainWindow", "D/A Bipolar Ieșire în tensiune"))
        self.comboBoxSchemeType.setItemText(2, _translate("MainWindow", "D/A CMOS   Ieșire in tensiune"))
        self.label_29.setText(_translate("MainWindow", "Tipul schemei:"))
        self.UnitTypeComboBox.setItemText(0, _translate("MainWindow", "s"))
        self.UnitTypeComboBox.setItemText(1, _translate("MainWindow", "ms"))
        self.UnitTypeComboBox.setItemText(2, _translate("MainWindow", "us"))
        self.UnitTypeComboBox.setItemText(3, _translate("MainWindow", "ns"))
        self.label_12.setText(_translate("MainWindow", "Numar diviziuni:"))
        self.InfoPushButton.setText(_translate("MainWindow", "Informatii Semnal"))
        self.menuDocumenta_ie.setTitle(_translate("MainWindow", "Documentație"))
        self.action_ndrum_tor_laborator_EA.setText(_translate("MainWindow", "Îndrumător laborator EA"))
        self.actionPrezentare.setText(_translate("MainWindow", "Prezentare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
